### ISSUE TITLE
How to use the offloading in my MoE model?

### ISSUE THREAD

**Issue by WangRongsheng** [dvmazur/mixtral-offloading#13]

**Comment by WangRongsheng** [comment]
We fine-tuned Mixtral-8x7b with LoRA, and it performed well on Chinese chat. However even though we used int4 quantization it still requires 25GB of VRAM to run, we would like to know how to use offloading in our model? Thank you!

- our model: https://github.com/WangRongsheng/Aurora

**Comment by dvmazur** [comment]
Hey, @WangRongsheng!

The code in this repository currently only supports [HQQ](https://github.com/mobiusml/hqq) quantized models, thus using it for your model won't be as straightforward.

If you don't know where to start, please read our [tech-report](https://arxiv.org/abs/2312.17238).

**Comment by WangRongsheng** [comment]
thx

**Comment by lavawolfiee** [comment]
Hello, @WangRongsheng!

As @dvmazur said, this repository currently supports only HQQ quantizaiton. But you can load our quantized model and add LoRA layers to it (I'm not sure whether peft.PeftModel will handle this correctly so it's possible that you will need to load them by hand). Note that LoRA weights should always reside on GPU because our offloading mechanism does not yet support custom weights offloading.
